# Automatic Dependabot version-update pull requests disabled at maintainer request on 2026-10-03.
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 0
    groups:
      npm-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 0
    groups:
      github-actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
